include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_put_required_named_parameters_first: true
    - always_use_package_imports: true
    - prefer_double_quotes: true
    - require_trailing_commas: true
    - sort_child_properties_last: true
    - sort_constructors_first: true
    - sort_unnamed_constructors_first: true