name: pokemon_app
description: "Application for viewing relevant information about the Pokémon saga."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.3.0
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  connectivity_plus: ^7.0.0
  slang: ^4.9.2
  slang_flutter: ^4.9.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  faker: ^2.2.0
  extended_image: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  slang_build_runner: ^4.9.0

flutter:
  uses-material-design: true

  assets:
    - .env
